service: auth-service
frameworkVersion: '2'

provider:
    name: aws
    runtime: nodejs12.x
    stage: dev
    region: eu-west-1

plugins:
    -   serverless-webpack

functions:
    basicAuthorizer:
        handler: handler.basicAuthorizer

custom:
    webpack:
        webpackConfig: './webpack.config.js'
        packager: 'npm'
        includeModules: true
