name: ProductCreateModel
contentType: 'application/json'
schema:
    type: object
    properties:
        title:
            type: string
        description:
            type: string
        price:
            type: number
        image:
            type: string
        count:
            type: number
