name: ProductModel
contentType: 'application/json'
schema:
    type: object
    properties:
        id:
            type: string
        title:
            type: string
        description:
            type: string
        price:
            type: number
        image:
            type: string
